// import TanStackProvider from '@/components/TanStackProvider/TanStackProvider';
// import type { Metadata } from 'next';
// // import { Geist, Geist_Mono } from 'next/font/google';         // Прибираємо!!!
// import './globals.css';
// import Header from '../components/Header/Header';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });
// прибираємо старі шрифти
// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

// ----------------Імпортуємо новий шрифт--------------------

// import { Lobster, Michroma, Roboto } from 'next/font/google';

// const roboto = Roboto({
//   subsets: ['latin'],
//   weight: ['400', '700'],
//   variable: '--font-roboto',
//   display: 'swap',
// });

// const lobster = Lobster({
//   subsets: ['latin'],
//   weight: ['400'],
//   variable: '--font-lobster',
//   display: 'swap',
// });

// const michroma = Michroma({
//   subsets: ['latin'],
//   weight: ['400'],
//   variable: '--font-michroma',
//   display: 'swap',
// });

// export const metadata: Metadata = {
//   title: 'NoteHub',
//   description: 'Generated by create next app',
//   openGraph: {
//     title: 'OpenGraph',
//     description: 'some description',
//     url: `https://www.edu.goit.global/uk`, // має бути реальна, робоча URL-а
//     siteName: 'NoteHub',
//     images: [
//       {
//         url: 'https://ac.goit.global/fullstack/react/og-meta.jpg',
//         width: 1200,
//         height: 630,
//         alt: 'background',
//       },
//     ],
//     type: 'article',
//   },
// };

// export default function RootLayout({
//   children,
//   modal,
// }: Readonly<{
//   children: React.ReactNode;
//   modal: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       {/* <body className={`${geistSans.variable} ${geistMono.variable}`}>   -- Прибираємо старі класи з <body>*/}

//       {/* додаємо клас у розмітку */}

//       <body
//         className={`${roboto.variable} ${lobster.variable} ${michroma.variable}`}
//       >
//         <TanStackProvider>
//           <Header />
//           <main>
//             {children}
//             {modal}
//           </main>
//           <hr />
//           <footer>
//             <p>{/* Created <time dateTime="2025">2025</time> */} FOOTER</p>
//           </footer>
//         </TanStackProvider>
//       </body>
//     </html>
//   );
// }

///////////////
/**Додаємо цей провайдер у layout.tsx, щоб дані про авторизацію були доступні в будь-якому компоненті застосунку: */
import TanStackProvider from '@/components/TanStackProvider/TanStackProvider';
import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';         // Прибираємо!!!
import './globals.css';
import Header from '../components/Header/Header';
import { Lobster, Michroma, Roboto } from 'next/font/google';
import AuthProvider from '@/components/AuthProvider/AuthProvider';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto',
  display: 'swap',
});

const lobster = Lobster({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-lobster',
  display: 'swap',
});

const michroma = Michroma({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-michroma',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'NoteHub',
  description: 'Generated by create next app',
  openGraph: {
    title: 'OpenGraph',
    description: 'some description',
    url: `https://www.edu.goit.global/uk`, // має бути реальна, робоча URL-а
    siteName: 'NoteHub',
    images: [
      {
        url: 'https://ac.goit.global/fullstack/react/og-meta.jpg',
        width: 1200,
        height: 630,
        alt: 'background',
      },
    ],
    type: 'article',
  },
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={`${geistSans.variable} ${geistMono.variable}`}>   -- Прибираємо старі класи з <body>*/}

      {/* додаємо клас у розмітку */}

      <body
        className={`${roboto.variable} ${lobster.variable} ${michroma.variable}`}
      >
        <TanStackProvider>
          <AuthProvider>
            <Header />
            <main>
              {children}
              {modal}
            </main>
            <hr />
            <footer>
              <p>{/* Created <time dateTime="2025">2025</time> */} FOOTER</p>
            </footer>
          </AuthProvider>
        </TanStackProvider>
      </body>
    </html>
  );
}
